#!/usr/bin/env rake
require "bundler/gem_tasks"
require 'rake'
require 'rake/testtask'

desc "Default Task"
task :default => [ :clean, :test ]

desc "Clean images generated by tests"
task :clean do
  rm FileList['test/output/*.png']
  rm_rf 'pkg'
  rm_rf 'doc'
end

# Run the unit tests
Rake::TestTask.new { |t|
  t.libs << "test"
  t.pattern = 'test/*_test.rb'
  t.verbose = true
}
